# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://tctorz.github.io/
date_format: "ordinal"
title: 李健的博客
subtitle: "一个简单的博客"
description: "李健的个人博客"
keywords: 日志, Jian Li, ifwechat, ifwechat.com, Web前端程序员, PHP程序员
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5
repository: TctOrz/tctorz.github.io
# 对 css 和 js 资源的 cdn 加速配置
cdn:
    jsdelivr:
        enabled: true
# 组件配置
components:
    # 分享
    share:
        enabled: false
    # 不蒜子访问统计
    busuanzi:
        enabled: true
        start_date: 2020-06-15
# 压缩页面内容
compress_html:
  clippings: all
  comments: ["<!--", "-->"]
# 文章字数统计
word_count:
    enabled: true

# ---------------- #
#      Author      #
# ---------------- #
author: Jian Li
organization: 
organization_url: 
github_username: TcTOrz
location: Nanjing, China
email: cat_lijian@foxmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

#   -
#     href: /archives/
#     label: 归档

#   -
#     href: /open-source/
#     label: 开源

  -
    href: /wiki/
    label: 维基

#   -
#     href: /links/
#     label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
plugins:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: 
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: TcTOrz
    repo: blog-comments
    oauth:
        client_id: b5e12eb2c1d3152c681d
        client_secret: c3de57a05164ab3526f28d499ffc39c90450fffc
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: TcTOrz
    repo: blog-comments
    clientID: b5e12eb2c1d3152c681d
    clientSecret: c3de57a05164ab3526f28d499ffc39c90450fffc
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#      Google      #
# ---------------- #
google:
    analytics_id: UA-80669434-1
    adsense:
        footer: true
        sidebar: true 
        content_header: true
        content_footer: false
